"""empty message

Revision ID: 7367fa5c2b29
Revises: 
Create Date: 2024-12-19 14:36:38.362094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7367fa5c2b29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('photo', postgresql.BYTEA(), nullable=True),
    sa.Column('liked_manga', sa.Uuid(), nullable=True),
    sa.Column('your_works', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('Читатель', 'Художник', 'Бета', 'Тайпер', 'Редактор', name='role'), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('liked_manga',
    sa.Column('like_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('manga_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liked_manga')
    op.drop_table('user')
    # ### end Alembic commands ###
